

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataTicketChart.Models.Domain
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class EnFormaEntities : DbContext
{
    public EnFormaEntities()
        : base("name=EnFormaEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<TblRecordTicket> TblRecordTicket { get; set; }

    public virtual DbSet<TblRecordsSocio> TblRecordsSocio { get; set; }

    public virtual DbSet<TblHistorialPeso> TblHistorialPeso { get; set; }

    public virtual DbSet<TblRecord> TblRecord { get; set; }

    public virtual DbSet<TBL_PERFILES> TBL_PERFILES { get; set; }

    public virtual DbSet<TBL_USUARIOS> TBL_USUARIOS { get; set; }

    public virtual DbSet<TblEmpleado> TblEmpleado { get; set; }

    public virtual DbSet<TblSocio> TblSocio { get; set; }


    public virtual int add_HistorialPesoSocio(Nullable<int> id_socio, Nullable<decimal> peso, Nullable<decimal> pesoi, Nullable<decimal> pesob, Nullable<decimal> abdai, Nullable<decimal> abda, Nullable<decimal> abdab, Nullable<decimal> abdbi, Nullable<decimal> abdb, Nullable<decimal> abdbb, Nullable<decimal> caderai, Nullable<decimal> cadera, Nullable<decimal> caderatb, Nullable<decimal> altura, string talla, Nullable<decimal> grasac, Nullable<decimal> imc, Nullable<decimal> ta, Nullable<decimal> guia, string observaciones)
    {

        var id_socioParameter = id_socio.HasValue ?
            new ObjectParameter("id_socio", id_socio) :
            new ObjectParameter("id_socio", typeof(int));


        var pesoParameter = peso.HasValue ?
            new ObjectParameter("peso", peso) :
            new ObjectParameter("peso", typeof(decimal));


        var pesoiParameter = pesoi.HasValue ?
            new ObjectParameter("pesoi", pesoi) :
            new ObjectParameter("pesoi", typeof(decimal));


        var pesobParameter = pesob.HasValue ?
            new ObjectParameter("pesob", pesob) :
            new ObjectParameter("pesob", typeof(decimal));


        var abdaiParameter = abdai.HasValue ?
            new ObjectParameter("abdai", abdai) :
            new ObjectParameter("abdai", typeof(decimal));


        var abdaParameter = abda.HasValue ?
            new ObjectParameter("abda", abda) :
            new ObjectParameter("abda", typeof(decimal));


        var abdabParameter = abdab.HasValue ?
            new ObjectParameter("abdab", abdab) :
            new ObjectParameter("abdab", typeof(decimal));


        var abdbiParameter = abdbi.HasValue ?
            new ObjectParameter("abdbi", abdbi) :
            new ObjectParameter("abdbi", typeof(decimal));


        var abdbParameter = abdb.HasValue ?
            new ObjectParameter("abdb", abdb) :
            new ObjectParameter("abdb", typeof(decimal));


        var abdbbParameter = abdbb.HasValue ?
            new ObjectParameter("abdbb", abdbb) :
            new ObjectParameter("abdbb", typeof(decimal));


        var caderaiParameter = caderai.HasValue ?
            new ObjectParameter("caderai", caderai) :
            new ObjectParameter("caderai", typeof(decimal));


        var caderaParameter = cadera.HasValue ?
            new ObjectParameter("cadera", cadera) :
            new ObjectParameter("cadera", typeof(decimal));


        var caderatbParameter = caderatb.HasValue ?
            new ObjectParameter("caderatb", caderatb) :
            new ObjectParameter("caderatb", typeof(decimal));


        var alturaParameter = altura.HasValue ?
            new ObjectParameter("altura", altura) :
            new ObjectParameter("altura", typeof(decimal));


        var tallaParameter = talla != null ?
            new ObjectParameter("talla", talla) :
            new ObjectParameter("talla", typeof(string));


        var grasacParameter = grasac.HasValue ?
            new ObjectParameter("grasac", grasac) :
            new ObjectParameter("grasac", typeof(decimal));


        var imcParameter = imc.HasValue ?
            new ObjectParameter("imc", imc) :
            new ObjectParameter("imc", typeof(decimal));


        var taParameter = ta.HasValue ?
            new ObjectParameter("ta", ta) :
            new ObjectParameter("ta", typeof(decimal));


        var guiaParameter = guia.HasValue ?
            new ObjectParameter("guia", guia) :
            new ObjectParameter("guia", typeof(decimal));


        var observacionesParameter = observaciones != null ?
            new ObjectParameter("observaciones", observaciones) :
            new ObjectParameter("observaciones", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_HistorialPesoSocio", id_socioParameter, pesoParameter, pesoiParameter, pesobParameter, abdaiParameter, abdaParameter, abdabParameter, abdbiParameter, abdbParameter, abdbbParameter, caderaiParameter, caderaParameter, caderatbParameter, alturaParameter, tallaParameter, grasacParameter, imcParameter, taParameter, guiaParameter, observacionesParameter);
    }


    public virtual ObjectResult<sel_HistorialPeso_Result> sel_HistorialPeso(Nullable<int> id_socio)
    {

        var id_socioParameter = id_socio.HasValue ?
            new ObjectParameter("id_socio", id_socio) :
            new ObjectParameter("id_socio", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_HistorialPeso_Result>("sel_HistorialPeso", id_socioParameter);
    }


    public virtual ObjectResult<sel_socio_new_Result> sel_socio_new()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_socio_new_Result>("sel_socio_new");
    }


    public virtual int add_HistorialPesoSocio1(Nullable<int> id_socio, Nullable<decimal> pesoInicial, Nullable<decimal> pesoBajado, Nullable<decimal> pesoActual, Nullable<decimal> circCinturaInicial, Nullable<decimal> circCinturaBajado, Nullable<decimal> circCinturaActual, Nullable<decimal> circCaderaInicial, Nullable<decimal> circCaderaBajado, Nullable<decimal> circCaderaActual, Nullable<decimal> circPechoInicial, Nullable<decimal> circPechoBajado, Nullable<decimal> circPechoActual, Nullable<decimal> altura, string talla, Nullable<decimal> grasaCorporal, Nullable<decimal> edad, Nullable<decimal> frecCardicaMaxima, Nullable<decimal> frecCardicaReposo, Nullable<decimal> porceEntrenamiento, Nullable<decimal> imc, Nullable<decimal> pie, string guia, string observaciones)
    {

        var id_socioParameter = id_socio.HasValue ?
            new ObjectParameter("id_socio", id_socio) :
            new ObjectParameter("id_socio", typeof(int));


        var pesoInicialParameter = pesoInicial.HasValue ?
            new ObjectParameter("pesoInicial", pesoInicial) :
            new ObjectParameter("pesoInicial", typeof(decimal));


        var pesoBajadoParameter = pesoBajado.HasValue ?
            new ObjectParameter("pesoBajado", pesoBajado) :
            new ObjectParameter("pesoBajado", typeof(decimal));


        var pesoActualParameter = pesoActual.HasValue ?
            new ObjectParameter("pesoActual", pesoActual) :
            new ObjectParameter("pesoActual", typeof(decimal));


        var circCinturaInicialParameter = circCinturaInicial.HasValue ?
            new ObjectParameter("circCinturaInicial", circCinturaInicial) :
            new ObjectParameter("circCinturaInicial", typeof(decimal));


        var circCinturaBajadoParameter = circCinturaBajado.HasValue ?
            new ObjectParameter("circCinturaBajado", circCinturaBajado) :
            new ObjectParameter("circCinturaBajado", typeof(decimal));


        var circCinturaActualParameter = circCinturaActual.HasValue ?
            new ObjectParameter("circCinturaActual", circCinturaActual) :
            new ObjectParameter("circCinturaActual", typeof(decimal));


        var circCaderaInicialParameter = circCaderaInicial.HasValue ?
            new ObjectParameter("circCaderaInicial", circCaderaInicial) :
            new ObjectParameter("circCaderaInicial", typeof(decimal));


        var circCaderaBajadoParameter = circCaderaBajado.HasValue ?
            new ObjectParameter("circCaderaBajado", circCaderaBajado) :
            new ObjectParameter("circCaderaBajado", typeof(decimal));


        var circCaderaActualParameter = circCaderaActual.HasValue ?
            new ObjectParameter("circCaderaActual", circCaderaActual) :
            new ObjectParameter("circCaderaActual", typeof(decimal));


        var circPechoInicialParameter = circPechoInicial.HasValue ?
            new ObjectParameter("circPechoInicial", circPechoInicial) :
            new ObjectParameter("circPechoInicial", typeof(decimal));


        var circPechoBajadoParameter = circPechoBajado.HasValue ?
            new ObjectParameter("circPechoBajado", circPechoBajado) :
            new ObjectParameter("circPechoBajado", typeof(decimal));


        var circPechoActualParameter = circPechoActual.HasValue ?
            new ObjectParameter("circPechoActual", circPechoActual) :
            new ObjectParameter("circPechoActual", typeof(decimal));


        var alturaParameter = altura.HasValue ?
            new ObjectParameter("altura", altura) :
            new ObjectParameter("altura", typeof(decimal));


        var tallaParameter = talla != null ?
            new ObjectParameter("talla", talla) :
            new ObjectParameter("talla", typeof(string));


        var grasaCorporalParameter = grasaCorporal.HasValue ?
            new ObjectParameter("grasaCorporal", grasaCorporal) :
            new ObjectParameter("grasaCorporal", typeof(decimal));


        var edadParameter = edad.HasValue ?
            new ObjectParameter("edad", edad) :
            new ObjectParameter("edad", typeof(decimal));


        var frecCardicaMaximaParameter = frecCardicaMaxima.HasValue ?
            new ObjectParameter("frecCardicaMaxima", frecCardicaMaxima) :
            new ObjectParameter("frecCardicaMaxima", typeof(decimal));


        var frecCardicaReposoParameter = frecCardicaReposo.HasValue ?
            new ObjectParameter("frecCardicaReposo", frecCardicaReposo) :
            new ObjectParameter("frecCardicaReposo", typeof(decimal));


        var porceEntrenamientoParameter = porceEntrenamiento.HasValue ?
            new ObjectParameter("porceEntrenamiento", porceEntrenamiento) :
            new ObjectParameter("porceEntrenamiento", typeof(decimal));


        var imcParameter = imc.HasValue ?
            new ObjectParameter("imc", imc) :
            new ObjectParameter("imc", typeof(decimal));


        var pieParameter = pie.HasValue ?
            new ObjectParameter("pie", pie) :
            new ObjectParameter("pie", typeof(decimal));


        var guiaParameter = guia != null ?
            new ObjectParameter("guia", guia) :
            new ObjectParameter("guia", typeof(string));


        var observacionesParameter = observaciones != null ?
            new ObjectParameter("observaciones", observaciones) :
            new ObjectParameter("observaciones", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_HistorialPesoSocio1", id_socioParameter, pesoInicialParameter, pesoBajadoParameter, pesoActualParameter, circCinturaInicialParameter, circCinturaBajadoParameter, circCinturaActualParameter, circCaderaInicialParameter, circCaderaBajadoParameter, circCaderaActualParameter, circPechoInicialParameter, circPechoBajadoParameter, circPechoActualParameter, alturaParameter, tallaParameter, grasaCorporalParameter, edadParameter, frecCardicaMaximaParameter, frecCardicaReposoParameter, porceEntrenamientoParameter, imcParameter, pieParameter, guiaParameter, observacionesParameter);
    }


    public virtual ObjectResult<sel_HistorialPesoSocio_Result> sel_HistorialPesoSocio(Nullable<int> id_socio)
    {

        var id_socioParameter = id_socio.HasValue ?
            new ObjectParameter("id_socio", id_socio) :
            new ObjectParameter("id_socio", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_HistorialPesoSocio_Result>("sel_HistorialPesoSocio", id_socioParameter);
    }


    public virtual ObjectResult<sel_byId_empleado_Result> sel_byId_empleado(Nullable<int> id_empleado)
    {

        var id_empleadoParameter = id_empleado.HasValue ?
            new ObjectParameter("id_empleado", id_empleado) :
            new ObjectParameter("id_empleado", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_byId_empleado_Result>("sel_byId_empleado", id_empleadoParameter);
    }


    public virtual ObjectResult<sel_empleado_new_Result1> sel_empleado_new()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sel_empleado_new_Result1>("sel_empleado_new");
    }

}

}

