
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataTicketChart.Models.Domain
{

using System;
    
public partial class sel_empleado_new_Result1
{

    public int id_empleado { get; set; }

    public int num_empleado { get; set; }

    public string nombre { get; set; }

    public string ap_paterno { get; set; }

    public string ap_materno { get; set; }

}

}
