
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataTicketChart.Models.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_USUARIOS
{

    public int ID_USUARIO { get; set; }

    public string NOMBRE { get; set; }

    public string APELLIDO_PAT { get; set; }

    public string APELLIDO_MAT { get; set; }

    public int ID_AREA { get; set; }

    public string USUARIO { get; set; }

    public string PASSWORD { get; set; }

    public int ID_PERFIL { get; set; }

    public bool ACTIVO { get; set; }

    public System.DateTime CREADO { get; set; }

    public string CREADOPOR { get; set; }

    public System.DateTime ACTUALIZADO { get; set; }

    public string ACTUALIZADOPOR { get; set; }



    public virtual TBL_PERFILES TBL_PERFILES { get; set; }

}

}
