
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataTicketChart.Models.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class TblHistorialPeso
{

    public int id_historial { get; set; }

    public int id_socio { get; set; }

    public decimal prev_peso { get; set; }

    public decimal prev_alto { get; set; }

    public decimal prev_bajo { get; set; }

    public decimal prev_pecho { get; set; }



    public virtual TblSocio TblSocio { get; set; }

}

}
