
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataTicketChart.Models.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class TblRecordTicket
{

    public int id_record_ticket { get; set; }

    public int id_socio { get; set; }

    public decimal pliegueTricipal { get; set; }

    public decimal pliegueEscapular { get; set; }

    public decimal trigliceridos { get; set; }

    public decimal Colesterol { get; set; }

    public decimal Glucosa { get; set; }

    public decimal frecuenciaCardiaca { get; set; }

    public decimal frecuanciArtSisfolica { get; set; }

    public decimal frecuanciArtDiasfolica { get; set; }

    public decimal porcentajeCargaPecho { get; set; }

    public decimal porcentajeCargaPierna { get; set; }

    public decimal metabolismoBasal { get; set; }



    public virtual TblSocio TblSocio { get; set; }

}

}
